name: Sync

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 
  
jobs:
  sync-repo-branch:
    runs-on: ubuntu-latest
    name: Sync latest commits from the repo branch

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        ref: repo
        persist-credentials: false
        
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: repo
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: repo
        upstream_sync_repo: keiyoushi/extensions
        test_mode: false
      
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
      
  sync-gh-pages-branch:
    runs-on: ubuntu-latest
    name: Sync latest commits from the gh-pages branch

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        persist-credentials: false

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: gh-pages
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: gh-pages
        upstream_sync_repo: keiyoushi/extensions
        test_mode: false
      
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}

  sync-extensions-source-repository:
    runs-on: ubuntu-latest
    name: Sync latest commits from the extensions-source repository

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        ref: extensions-source
        persist-credentials: false

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: extensions-source
        target_repo_token: ${{ secrets.WORKFLOW_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: keiyoushi/extensions-source
        test_mode: false

    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
